// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY9e12eVJIILFF04LCEE9CES_m5h1Jjjo',
    appId: '1:58271761420:web:bfb3cab9cbf47b5e511a29',
    messagingSenderId: '58271761420',
    projectId: 'flutter-nilium',
    authDomain: 'flutter-nilium.firebaseapp.com',
    storageBucket: 'flutter-nilium.appspot.com',
    measurementId: 'G-Y1BFMW05SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYOXijr-QI-fC6oQyfd6rqp1OR0w2AFpw',
    appId: '1:58271761420:android:0989d78126276537511a29',
    messagingSenderId: '58271761420',
    projectId: 'flutter-nilium',
    storageBucket: 'flutter-nilium.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NnkSH-DOdDKDte7rG-ozpxN_b6ufOAA',
    appId: '1:58271761420:ios:da52907d8e08dd4c511a29',
    messagingSenderId: '58271761420',
    projectId: 'flutter-nilium',
    storageBucket: 'flutter-nilium.appspot.com',
    iosBundleId: 'com.example.nilium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NnkSH-DOdDKDte7rG-ozpxN_b6ufOAA',
    appId: '1:58271761420:ios:c3f92a82668755c7511a29',
    messagingSenderId: '58271761420',
    projectId: 'flutter-nilium',
    storageBucket: 'flutter-nilium.appspot.com',
    iosBundleId: 'com.example.nilium.RunnerTests',
  );
}
